const canales = [
  'https://latamvidzfy.org/caze2.php',
  'https://latamvidzfy.org/caze1.php',
  'https://esvidzypro.sbs/dsportsar.php',
  'https://esvidzypro.sbs/caze2.php',
  'https://esvidzypro.sbs/daserste.php',
  'https://latamvidzfy.org/dsportsplus.php',  
  'https://esvidzy99.co/caracoltv.php',
  'https://esvidzypro.sbs/tvela1.php',
  'https://esvidzy99.co/caracoltv.php',
  'https://latamvidzfy.org/tudnmx.php',
  'https://esvidzy99.co/caracoltv.php',
  'https://sudamericaplay.sbs/canal_41/trecepy.php',
'https://latamvidzfy.org/trece.php',
'https://latamvidzfy.org/rpc.php',
'https://latamvidzfy.org/tvela1.php',
  'https://latamvidzfy.org/dsportsar.php',
'https://latamvidzfy.org/m6.php',
'https://latamvidzfy.org/daserstepr.php',
'https://latamvidzfye.org/zdfpr.php',
'https://latamvidzfy.org/unicanal.php',
'https://latamvidzfy.org/sportvbr.php',
'https://esvidzy99.co/caracoltv.php',
'https://latamvidzs.org/canal.php?stream=tycsports',
'https://latamvidzfy.org/fox1us.php',
  'https://latamvidzs.org/canal.php?stream=disney2'

];
